spring:
  datasource:
    username: root
    password: 1qaz1qaz
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nembers
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true