spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true

#  h2:
#    console:
#      enabled: true